Adapt 4122
SU-SWS/ood_giving_site pull request #239
Opened 2021-12-06 21:39 UTC by Lyafel

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2021-12-07 00:35 UTC, yvonnetangsu commented on src/components/composite/oodGallerySlideshow.js
> +  const [modalSlideshow, setModalSlideshow] = useState(null);
@Lyafel This works, but is there a reason that you use useState instead of useRef to set the reference for the slideshow and modal slidershow?

2021-12-07 00:36 UTC, yvonnetangsu reviewed
@Lyafel Added a question about useState vs useRef - thanks

2021-12-07 22:15 UTC, Lyafel commented
@yvonnetangsu No reason, just added the second slider as the first one was added. Changed them both.

2021-12-07 22:37 UTC, yvonnetangsu requested changes
@Lyafel I believe you might need to change the next/prev click functions also. They're not working currently.

2021-12-08 05:46 UTC, sherakama commented
There are a bunch of errors in the console log and the page crashes for me when using the non-modal arrows.

See: https://share.getcloudapp.com/4guPoQKQ

```
Warning: React does not recognize the `currentSlide` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `currentslide` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at PrevArrow (webpack-internal:///./node_modules/react-slick/lib/arrows.js:52:5)
    at div
    at InnerSlider (webpack-internal:///./node_modules/react-slick/lib/inner-slider.js:70:5)
    at Slider (webpack-internal:///./node_modules/react-slick/lib/slider.js:60:5)
	...
```

```
react-dom.development.js:67 Warning: React does not recognize the `slideCount` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `slidecount` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at PrevArrow (webpack-internal:///./node_modules/react-slick/lib/arrows.js:52:5)
    at div
    at InnerSlider (webpack-internal:///./node_modules/react-slick/lib/inner-slider.js:70:5)
    at Slider (webpack-internal:///./node_modules/react-slick/lib/slider.js:60:5)
	...
```

2021-12-08 07:41 UTC, yvonnetangsu approved these changes
Thanks for the fix, @Lyafel! Everything seems to be all working well now!

2021-12-08 07:42 UTC, yvonnetangsu commented
> There are a bunch of errors in the console log and the page crashes for me when using the non-modal arrows.
> 
> See: https://share.getcloudapp.com/4guPoQKQ
> 
> ```
> Warning: React does not recognize the `currentSlide` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `currentslide` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     at button
>     at PrevArrow (webpack-internal:///./node_modules/react-slick/lib/arrows.js:52:5)
>     at div
>     at InnerSlider (webpack-internal:///./node_modules/react-slick/lib/inner-slider.js:70:5)
>     at Slider (webpack-internal:///./node_modules/react-slick/lib/slider.js:60:5)
> 	...
> ```
> 
> ```
> react-dom.development.js:67 Warning: React does not recognize the `slideCount` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `slidecount` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     at button
>     at PrevArrow (webpack-internal:///./node_modules/react-slick/lib/arrows.js:52:5)
>     at div
>     at InnerSlider (webpack-internal:///./node_modules/react-slick/lib/inner-slider.js:70:5)
>     at Slider (webpack-internal:///./node_modules/react-slick/lib/slider.js:60:5)
> 	...
> ```

Looks like it's caused by not adding `.current` after the slideshow refs when changed from useState to useRef. Seems to be all working now 😄

2021-12-08 17:04 UTC, sherakama approved these changes
ty

2021-12-08 17:05 UTC, merged